name: Keep Render Alive

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Server
        run: curl -s ${{ secrets.RENDER_URL }}/health || true